# cosim/pwl_writer.py
"""
PWL (Piecewise Linear) bridge file writer.

Generates .pwl files that bridge the Python-domain channel model
to the SPICE-domain receiver circuit. The key file is i_ph.pwl,
the time-varying photocurrent that drives the solar cell subcircuit.

Usage:
    from cosim.pwl_writer import write_photocurrent_pwl

    write_photocurrent_pwl(
        time, P_tx_waveform,
        responsivity=0.457, channel_gain=1.2e-3,
        filename='session/i_ph.pwl'
    )
"""

import numpy as np
from pathlib import Path
from typing import Optional


def write_photocurrent_pwl(time: np.ndarray,
                            P_tx: np.ndarray,
                            responsivity: float,
                            channel_gain: float,
                            filename,
                            led_name: str = '',
                            pv_name: str = '',
                            distance_m: float = 0.0) -> str:
    """
    Write photocurrent PWL file for SPICE simulation.

    Computes I_ph(t) = R_lambda * G_ch * P_tx(t) and writes as PWL pairs.

    Args:
        time: Time array (seconds)
        P_tx: Transmitted optical power waveform (W)
        responsivity: PV responsivity R_lambda (A/W)
        channel_gain: Optical channel gain H(0) (dimensionless)
        filename: Output file path
        led_name: LED part number (for header comment)
        pv_name: PV part number (for header comment)
        distance_m: Link distance (for header comment)

    Returns:
        Absolute path to written file
    """
    filename = Path(filename)
    filename.parent.mkdir(parents=True, exist_ok=True)

    # Compute photocurrent
    I_ph = responsivity * channel_gain * P_tx

    with open(filename, 'w') as f:
        # Header comments
        f.write(f"; Photocurrent PWL file for SPICE co-simulation\n")
        f.write(f"; Generated by cosim.pwl_writer\n")
        if led_name:
            f.write(f"; LED: {led_name}\n")
        if pv_name:
            f.write(f"; PV:  {pv_name}\n")
        if distance_m > 0:
            f.write(f"; Distance: {distance_m*100:.1f} cm\n")
        f.write(f"; R_lambda: {responsivity:.4f} A/W\n")
        f.write(f"; G_ch: {channel_gain:.6e}\n")
        f.write(f"; I_ph range: [{I_ph.min()*1e6:.2f}, {I_ph.max()*1e6:.2f}] uA\n")
        f.write(f"; Points: {len(time)}\n")
        f.write(f";\n")

        # PWL data pairs
        for t, i in zip(time, I_ph):
            f.write(f"{t:.10e} {i:.10e}\n")

    return str(filename.resolve())


def write_optical_power_pwl(time: np.ndarray,
                             P_rx: np.ndarray,
                             filename,
                             metadata: Optional[dict] = None) -> str:
    """
    Write received optical power PWL file.

    Args:
        time: Time array (seconds)
        P_rx: Received optical power (W)
        filename: Output path
        metadata: Optional dict of header metadata

    Returns:
        Absolute path to written file
    """
    filename = Path(filename)
    filename.parent.mkdir(parents=True, exist_ok=True)

    with open(filename, 'w') as f:
        f.write(f"; Received optical power PWL\n")
        if metadata:
            for k, v in metadata.items():
                f.write(f"; {k}: {v}\n")
        f.write(f"; Points: {len(time)}\n")
        f.write(f";\n")
        for t, p in zip(time, P_rx):
            f.write(f"{t:.10e} {p:.10e}\n")

    return str(filename.resolve())


def write_voltage_pwl(time: np.ndarray,
                       voltage: np.ndarray,
                       filename) -> str:
    """
    Write generic voltage PWL file.

    Args:
        time: Time array (s)
        voltage: Voltage array (V)
        filename: Output path

    Returns:
        Absolute path to written file
    """
    filename = Path(filename)
    filename.parent.mkdir(parents=True, exist_ok=True)

    with open(filename, 'w') as f:
        f.write(f"; Voltage PWL source\n")
        f.write(f"; Points: {len(time)}\n")
        for t, v in zip(time, voltage):
            f.write(f"{t:.10e} {v:.10e}\n")

    return str(filename.resolve())
